version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "pip"
    groups:
      python-packages:
        patterns: ["*"]
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "ci"
      - "dependencies"
    groups:
      github-actions:
        patterns: ["*"]
    ignore:
      - dependency-name: "actions/*"
        update-types: ["version-update:semver-patch"]
    open-pull-requests-limit: 5