name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          draft: false
          prerelease: false
          name: "Deep Research ${{github.ref_name}}"
          body: |
            ## Deep Research ${{github.ref_name}}
            
            Cette version inclut :
            - Améliorations de l'interface utilisateur
            - Optimisations de performance
            - Corrections de bugs
            
            ### Installation
            ```bash
            git clone https://github.com/${{ github.repository }}.git
            cd deep_research
            pip install -r requirements.txt
            ```
            
            Consultez le [README](https://github.com/${{ github.repository }}) pour les instructions détaillées.